// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7_lyYKtcYLONwM6OpWo0gm7hhJqcYCWU',
    appId: '1:1018957064862:android:00497e165b5a346e77298f',
    messagingSenderId: '1018957064862',
    projectId: 'kingseventgermany-e6a8f',
    databaseURL: 'https://kingseventgermany-e6a8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kingseventgermany-e6a8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvWCWyG2lcmCkQpAl56FF8aZJ1NGKbeQw',
    appId: '1:1018957064862:ios:55c6c95d2bff908377298f',
    messagingSenderId: '1018957064862',
    projectId: 'kingseventgermany-e6a8f',
    databaseURL: 'https://kingseventgermany-e6a8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kingseventgermany-e6a8f.appspot.com',
    iosBundleId: 'com.example.kingseventgermany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZHsYoOKeS4IVmweQzbqGzcaIdJW3RH6c',
    appId: '1:1018957064862:web:701c89c3ee97333d77298f',
    messagingSenderId: '1018957064862',
    projectId: 'kingseventgermany-e6a8f',
    authDomain: 'kingseventgermany-e6a8f.firebaseapp.com',
    databaseURL: 'https://kingseventgermany-e6a8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kingseventgermany-e6a8f.appspot.com',
    measurementId: 'G-6HXZ36677N',
  );
}
